### ISSUE TITLE
Unable to prepare setup for platform o365.calendar

### ISSUE THREAD

**Issue by jtsvba** [RogerSelwyn/O365-HomeAssistant#87]
Ever since I upgraded to version 2022.10 and higher, my o365.calendar would give me the following error:

ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform o365.calendar: Platform not found (cannot import name 'CalendarEventDevice' from 'homeassistant.components.calendar' (/usr/src/homeassistant/homeassistant/components/calendar/__init__.py)).

Any idea what's causing this in the latest versions? It works in 2022.9.7 but not higher than that...

**Comment by RogerSelwyn** [comment]
What version of the o365 integration are you using, are you on the latest version? Please post the full error, I think you have only posted the first line.

**Comment by RogerSelwyn** [comment]
This release (v3.1.0) in May solves your issue - https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v3.1.0

**Comment by jtsvba** [comment]
@RogerSelwyn thanks for your swift response! I figured I just had to update the application including the custom component files and configuration. Works like a charm now on the latest version of HA!
