### ISSUE TITLE
AttributeError: module 'homeassistant.util.dt' has no attribute 'get_default_time_zone'

### ISSUE THREAD

**Issue by rasssta** [RogerSelwyn/O365-HomeAssistant#238]
After upgrading to 4.8.1 (also exist in 4.8.0) I get the following error:

```
2024-06-18 11:07:03.876 ERROR (MainThread) [homeassistant.setup] Error during setup of component o365
  + Exception Group Traceback (most recent call last):
  |   File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/setup.py", line 404, in _async_setup_component
  |     result = await task
  |              ^^^^^^^^^^
  |   File "/home/homeassistant/.homeassistant/custom_components/o365/__init__.py", line 52, in async_setup
  |     await _async_setup_account(hass, account, conf_type)
  |   File "/home/homeassistant/.homeassistant/custom_components/o365/__init__.py", line 80, in _async_setup_account
  |     await do_setup(hass, account_conf, account, account_name, conf_type, perms)
  |   File "/home/homeassistant/.homeassistant/custom_components/o365/helpers/setup.py", line 66, in do_setup
  |     async with asyncio.TaskGroup() as group:
  |   File "/usr/lib/python3.12/asyncio/taskgroups.py", line 145, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (2 sub-exceptions)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/homeassistant/.homeassistant/custom_components/o365/helpers/setup.py", line 84, in _async_sensor_setup
    |     sensor_coordinator = O365SensorCordinator(hass, account_config)
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/homeassistant/.homeassistant/custom_components/o365/helpers/coordinator.py", line 89, in __init__
    |     1, 1, 1, 0, 0, 0, tzinfo=dt_util.get_default_time_zone()
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | AttributeError: module 'homeassistant.util.dt' has no attribute 'get_default_time_zone'. Did you mean: 'set_default_time_zone'?
    +---------------- 2 ----------------
    | Traceback (most recent call last):
    |   File "/home/homeassistant/.homeassistant/custom_components/o365/helpers/setup.py", line 94, in _async_email_setup
    |     email_coordinator = O365EmailCordinator(hass, account_config)
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/homeassistant/.homeassistant/custom_components/o365/helpers/coordinator.py", line 401, in __init__
    |     1, 1, 1, 0, 0, 0, tzinfo=dt_util.get_default_time_zone()
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | AttributeError: module 'homeassistant.util.dt' has no attribute 'get_default_time_zone'. Did you mean: 'set_default_time_zone'?
    +------------------------------------
```
I'm running HASS core 2024.5.5.
